/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.revolut.task;

import static spark.Spark.*;
import com.google.gson.Gson;
import com.revolut.task.exception.AccountNotFoundException;
import com.revolut.task.model.Account;


public class App {
    public static void main(String[] args) {
       Gson gson = new Gson();

       get("/:id", (req, res) -> AccountService.getAccount(req.params("id")), gson::toJson);
       post("/", (req, res) -> AccountService.createAccount(), gson::toJson);
       delete("/:id", (req, res) -> AccountService.deleteAccount(req.params("id")), gson::toJson);
       put("/:id", (req, res) -> {
           Account acc = gson.fromJson(req.body(), Account.class);

           //TODO: handle empty body
           return AccountService.updateAccount(req.params("id"), acc.getAmount());
       }, gson::toJson);

       exception(AccountNotFoundException.class, (exception, request, response) -> {
            response.type("application/json");
            response.body("{\"message\":\"Account not found\"}");
        });
    }
}
