/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package com.revolut.task

import spock.lang.Specification

class AccountServiceTest extends Specification {
    def "application has a greeting"() {
        setup:
        def app = new AccountService()

        when:
        def result = app.getAccount()

        then:
        result != null
        result == "Hello world"
    }
}
